server:
  port: 18081
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.dubbo.demo.provider.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
    # address: nacos://127.0.0.1:8848

spring:
  application:
    # Dubbo 应用名称
    name: springcloud-dubbo-provider
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848